dist: trusty
language:
  - ruby

rvm:
  - 2.5.7

services:
  - docker

addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "pamanda"
    token: ${SONAR_TOKEN}
  
cache:
  directories:
    - bundler

before_install:
  - gem install bundler:2.2.0
  - bundle install

stages:
  - Build and Test
  - Quality gate

jobs:
  include:
    - stage: Build and Test
      name: Build and Test
      script:
        - bundle exec rake db:create RAILS_ENV=test
        # - psql -c 'create database travis_ci_test;' -U postgres
        - bundle exec rake db:migrate RAILS_ENV=test
        - bundle exec rails test

    - stage: Quality gate
      name: Quality gate
      script:
        - sonar-scanner
