dist: trusty
language:
  - ruby

rvm:
  - 2.5.7

services:
  - docker

addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "pamanda"
    token: ${SONAR_TOKEN}

before_install:
  - gem install bundler:2.2.0
  - bundle install
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

stages:
  # - Build
  - Test
  - Quality gate

jobs:
  include:
    # - stage: Build
    #   name: Build
    #   script:
    #     - yarn build

    - stage: Test
      script:
        - bundle exec rails test

    - stage: Quality gate
      script:
        - sonar-scanner
