dist: trusty
language:
  - ruby

rvm:
  - 2.5.7

services:
  - docker

addons:
  postgresql: "9.6"
  sonarcloud:
    organization: "pamanda"
    token: ${SONAR_TOKEN}
  
cache:
  directories:
    - bundler

before_install:
  - gem install bundler:2.2.0

stages:
  - Build
  - Test
  - Quality gate

jobs:
  include:
    - stage: Build
      name: Build
      script:
        - bundle install
        - psql -c 'create database travis_ci_test;' -U postgres
        - bundle exec rake db:migrate RAILS_ENV=test

    - stage: Test
      name: Test
      script:
        - bundle exec rails test

    - stage: Quality gate
      name: Quality gate
      script:
        - sonar-scanner
