dist: trusty
language:
  - ruby

rvm:
  - 2.5.7

services:
  - docker

before_install:
  - gem install bundler:2.2.0
  - bundle install

stages:
  # - Build
  - Test
  # - Quality gate

jobs:
  include:
    # - stage: Build
    #   name: Build
    #   script:
    #     - yarn build

    - stage: Test
      script:
        - bundle exec rails test

    # - stage: Quality gate
    #   script:
    #     - sonar-scanner
