dist: trusty
language:
  - ruby

rvm:
  - 2.5.7

services:
  - docker
  - postgresql

before_install:
  - gem install bundler:2.2.0
  - bundle install
  # - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:migrate

stages:
  # - Build
  - Test
  # - Quality gate

jobs:
  include:
    # - stage: Build
    #   name: Build
    #   script:
    #     - yarn build

    - stage: Test
      script:
        - bundle exec rails test

    # - stage: Quality gate
    #   script:
    #     - sonar-scanner
