default:
  adapter: postgresql
  encoding: unicode
  database: '<%= ENV['DATABASE_NAME'] %>'
  username: '<%= ENV['DATABASE_USER'] %>'
  password: '<%= ENV['DATABASE_PASSWORD'] %>'
  port: 5432
  host: '<%= ENV['DATABASE_HOST'] %>'
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: '<%= ENV['DATABASE_NAME'] %>'
  username: '<%= ENV['DATABASE_USER'] %>'
  password: '<%= ENV['DATABASE_PASSWORD'] %>'
  port: 5432
  host: '<%= ENV['DATABASE_HOST'] %>'
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: travis_ci_test
production:
  adapter: postgresql
  encoding: unicode
  database: '<%= ENV['DATABASE_NAME'] %>'
  username: '<%= ENV['DATABASE_USER'] %>'
  password: '<%= ENV['DATABASE_PASSWORD'] %>'
  port: 5432
  host: '<%= ENV['DATABASE_HOST'] %>'
  pool: 5
  timeout: 5000
